stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - build
  script:
    - docker-compose build
  when: always

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - docker-compose up -d
  when: on_successm